version: '3.9'
services:
  server:
    image: backend-express
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    image: frontend-react
    depends_on:
      - server
    ports:
      - "80:80"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge
